import type * as iconNames from '../generated/Icons/index.js';

export const icons: Record<'Standard' | 'Brand' | 'Third-Party', (keyof typeof iconNames)[]> = {
  Standard: [
    'AlertIcon',
    'ArrowUpIcon',
    'ArrowRightIcon',
    'ArrowDownIcon',
    'ArrowLeftIcon',
    'CalendarIcon',
    'CaretUpIcon', // 'ChevronUpIcon',
    'CaretRightIcon', // 'ChevronRightIcon',
    'CaretDownIcon', // 'ChevronDownIcon',
    'CaretLeftIcon',
    'CheckmarkIcon',
    'CheckCircleIcon', // 'SuccessIcon',
    'CloseIcon',
    'CreateIcon',
    'DotIcon',
    'FolderIcon',
    'HelpIcon',
    'HistoryIcon',
    'HomeIcon',
    'InfoIcon',
    'LinkIcon',
    'MenuIcon',
    'MoreHorizIcon',
    'MoreVertIcon',
    'MutedIcon',
    'PauseIcon',
    'PersonIcon',
    'PlayIcon',
    'PlayCircleIcon',
    'PlusIcon',
    'RefreshIcon',
    'SaveIcon',
    'SaveFilledIcon',
    'SearchIcon',
    'SettingsIcon',
    'ShareIcon',
    'ShareAndroidIcon',
    'ShareAppleIcon',
    'StarIcon',
    'UnmutedIcon',
  ],
  Brand: [
    'TheAthleticIcon',
    'CookingIcon',
    'GamesIcon',
    'NewspaperIcon',
    'SuperTIcon',
    'WirecutterIcon',
  ],
  'Third-Party': ['AppleIcon', 'FacebookIcon', 'GoogleIcon'],
};
